### ISSUE TITLE
Is that possible can you compile to execute file?

### ISSUE THREAD

**Issue by odinchang2022** [DragoQCC/HardHatC2#11]

**Comment by DragoQCC** [comment]
Hi, can you give some detail here? If you mean for the teamserver and client, then you could compile them in visual studio, but you would still need the .net core runtime anyway so starting them with `dot net run` is the easiest. If you mean for the implant, once you start the teamserver and client, log in as the admin user, go to the settings, and make a new user. Log in as that new user, create a manager, and then go to the engineer page and fill in the info there you can select exe to have the implant created as an executable file.
