### ISSUE TITLE
mac os there is a problem????

### ISSUE THREAD

**Issue by pullghjunkkk** [DragoQCC/HardHatC2#20]
Users/chikkachun/.zprofile:21: no such file or directory: /opt/homebrew/bin/brew
/Users/chikkachun/.zprofile:22: no such file or directory: /opt/homebrew/bin/brew
/dev/fd/12:18: command not found: compdef
chikkachun@chikdeMBP HardHatC2-0.2.01-Alpha % the teamse
zsh: command not found: the
chikkachun@chikdeMBP HardHatC2-0.2.01-Alpha % the teamse
zsh: command not found: the
chikkachun@chikdeMBP HardHatC2-0.2.01-Alpha % dotnet run

Welcome to .NET 7.0!
---------------------
SDK version: 7.0.400

telemetry
---------
.NET tools collect usage data to help us improve your experience. Data is collected by Microsoft and shared with the community. You can opt out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your preferred shell.

Read more about .NET CLI tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
ASP.NET Core HTTPS development credentials installed.
To trust the certificate, execute 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn more about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Learn about new features: https://aka.ms/dotnet-whats-new
Explore docs: https://aka.ms/dotnet-docs
Report issues and find sources on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or browse: https://aka.ms/dotnet-cli
-------------------------------------------------- ------------------------------------
Could not find the project to execute. Make sure the project exists in /Users/chikkachun/Documents/HardHatC2-0.2.01-Alpha, or pass the path to the project with --project.
chikkachun@chikdeMBP HardHatC2-0.2.01-Alpha % dotnet run https://127.0.0.1:6000
Could not find the project to execute. Make sure the project exists in /Users/chikkachun/Documents/HardHatC2-0.2.01-Alpha, or pass the path to the project with --project.
chikkachun@chikdeMBP HardHatC2-0.2.01-Alpha %

**Comment by pullghjunkkk** [comment]
login request started
Connection refused (localhost:5000)
login request started
Connection refused (localhost:5000)
login request started
Connection refused (localhost:5000)
login request started
Connection refused (localhost:5000)
login request started
Connection refused (localhost:5000)
login request started
Connection refused (localhost:5000)
login request started
Connection refused (localhost:5000)
login request started
Connection refused (localhost:5000)
login request started
Connection refused (localhost:5000)

**Comment by DragoQCC** [comment]
Seems like you only started the client and not the teamserver they are started separately

**Comment by pullghjunkkk** [comment]
i saw HardHat_Admin user (Password is printed on first TeamServer startup) but the password seems to be incorrect


TeamServer is running in development mode.
TeamServer is running on https://127.0.0.1:6000
Initiating SQLite server
Connecting to database
Connected to sqlite server
Creating tables
Creating default roles
Creating default admin[**] HardHat_Admin's password is ^aAT^5*yCeDEZQ%2eh&V, make sure to save this password, as on the next start of the server it will not be displayed again [**]
Filling teamserver from database
Generating unique encryption keys for pathing and metadata id
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://127.0.0.1:6000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]

**Comment by pullghjunkkk** [comment]
i use HardHat_Admin and password is ^aAT^5*yCeDEZQ%2eh&V 

but login request started
Connection refused (localhost:5000)
