### ISSUE TITLE
Persistence?

### ISSUE THREAD

**Issue by d3c0d3d** [DragoQCC/HardHatC2#22]
Hi, I looked at the project's documentation and I didn't see it mentioning persistence anywhere, and the question arose, if I want persistence of my implants will I have to implement it?
I would like more details on the best practices used for this project!

**Comment by DragoQCC** [comment]
I believe that things like persistence is best left to the operator to implement, The current engineer implant supports running native PEs, .net assemblies, BOFs, DLLs, and tools on the system like sc all of which can be used for persistence so I don't see the need to try and make commands for every persistence technique.
