### ISSUE TITLE
Teamserver page not loading

### ISSUE THREAD

**Issue by mellonaut** [DragoQCC/HardHatC2#24]
Want to check things out but I'm having trouble getting TeamServer running. Well, it's running, it's just not serving:

TeamServer is running in development mode.
TeamServer is running on https://127.0.0.1:5000
Initiating SQLite server
Connecting to database
Connected to sqlite server
Creating tables
Creating default roles
Creating default admin
Filling teamserver from database
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://127.0.0.1:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]

When I browse to the server, I I get the "phony site" warning and click through but I get:

This 127.0.0.1 page can’t be foundNo webpage was found for the web address: https://127.0.0.1:5000/
HTTP ERROR 404

Running from windows, tried edge and firefox, tried waiting for about ten minutes, too, in case it just took time. Code looks good though!

**Comment by DragoQCC** [comment]
Hey, so it seems like you also need to still start the client. Navigate to the `HardHatC2Client` folder and do dotnet run, then you should be able to browse to its default address of `https://127.0.0.1:7096`. If you are interested tho in messing with the API on the team server I think its "https://127.0.0.1:5000/swagger"

**Comment by DragoQCC** [comment]
cool, ill go ahead and close this then :) feel free to hop in the discord or bloodhound gang slack linked in the readme if you have more questions.
