### ISSUE TITLE
Upload file. Error in tasking. The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by tudorioan20** [DragoQCC/HardHatC2#26]
I uploaded the file rick.exe in the upload tab, but when I try to upload it to the computer via "upload /file http://127.0.0.1:8080/rick.exe /dest C:\Users\gigadmin\Desktop" i get the following errors:

> Error in tasking The filename, directory name, or volume label syntax is incorrect. : 'C:\Users\gigadmin\Desktop\HardHatC2-master\TeamServer\http:\127.0.0.1:8080\rick.exe'                                                                                         at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options) at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable 1 unixCreateMode) at System.IO.File.ReadAllBytes(String path)  at TeamServer.Utilities.Engineer_TaskPreProcess.PreProcessTask(EngineerTask currentTask, Engineer engineer) in C:\Users\gigadmin\Desktop\HardHatC2-master\TeamServer\Utilities\Engineer_TaskPreProcess.cs:line 193 at TeamServer.Services.Handle_Implants.Handle_Engineer.HandleEngineerAsync(EngineerMetadata engineermetadata, HttpContext httpContext) in C:\Users\gigadmin\Desktop\HardHatC2-master\TeamServer\Services\Handle_Implants\Handle_Engineer.cs:line 368                                                                                                                 

>fail: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[8] Failed to invoke hub method 'UpdateTaskResponseSeenNotif'.                                                              System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')                                                                                                     at System.Collections.Generic.List1.get_Item(Int32 index)                                                              at TeamServer.Services.HardHatHub.UpdateTaskResponseSeenNotif(String username, String taskid, String engineerId) in C:\Users\gigadmin\Desktop\HardHatC2-master\TeamServer\Services\HardHatHub.cs:line 390                                       at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher1.ExecuteMethod(ObjectMethodExecutor methodExecutor, Hub hub, Object[] arguments)                                                                                                 at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher1.<Invoke>g__ExecuteInvocation|18_0(DefaultHubDispatcher1 dispatcher, ObjectMethodExecutor methodExecutor, THub hub, Object[] arguments, AsyncServiceScope scope, IHubActivator`1 hubActivator, HubConnectionContext connection, HubMethodInvocationMessage hubMethodInvocationMessage, Boolean isStreamCall)   

`

**Comment by DragoQCC** [comment]
so the `/file` argument works by finding a file at the location given on the teamserver so if the file you want to upload is on the same machine as the teamserver at `c:\example\myfile.exe` and you want to upload it on the target to `c:\windows\tasks\myfile.exe` the command is `upload /file c:\example\myfile.exe /dest c:\windows\tasks\myfile.exe ` if the file is local to the client then provide the path to the file on the client but include the `/local` argument and it will read the file before sending it the task to the team server for processing.

**Comment by DragoQCC** [comment]
Marking as closed
