### ISSUE TITLE
Engineer account cannot be created

### ISSUE THREAD

**Issue by arishwani** [DragoQCC/HardHatC2#3]
Hi, 

I tried creating an Engineer account but nothing happens.

**Comment by arishwani** [comment]
This is what I see from the client side,

c2 hub create user called, invoking on ts
c2 hub create user called, invoking on ts
c2 hub create user called, invoking on ts
c2 hub create user called, invoking on ts
c2 hub create user called, invoking on ts


but nothing happens

**Comment by arishwani** [comment]
Issue is fixed, this can be closed. Thank you.

**Comment by DragoQCC** [comment]
yeah, I think this is because the client still launches, but if it starts before the teamserver the connection will not reset properly, going to look into fixing that thanks.
