### ISSUE TITLE
Error generating exe

### ISSUE THREAD

**Issue by Imanfeng** [DragoQCC/HardHatC2#9]
hi，server reported an error when I generated the payload
<img width="1919" alt="image" src="https://user-images.githubusercontent.com/24694387/231332745-ab67139f-b261-416e-9da3-29db019f9491.png">

<img width="656" alt="image" src="https://user-images.githubusercontent.com/24694387/231331805-106b0408-2b41-43b2-b549-8a9b4f91d615.png">
I am on OSX montery and Teamserver is on Windows

**Comment by Imanfeng** [comment]
I Use OSX to TeamServer is OK

**Comment by DragoQCC** [comment]
So just to confirm, changing to using OSX as your os for the teamserver to run on fixed your issue?
